### PR TITLE
Use dumb-init

### PR DESCRIPTION
**Pull request by ginkel**
While debugging #304 I noticed that the `pyouroboros/ouroboros` Docker image does not properly react to `SIGTERM`, but instead only terminates when forcibly killed by Docker (using `SIGKILL`) after a timeout. This change adds Yelp dumb-init [1] as entrypoint to restore proper signal handling (even when Ouroboros runs as PID 1).

[1] https://github.com/Yelp/dumb-init

### CODE REVIEW

**Comment by DirtyCajunRice** [comment]
I am not sure that this is the correct way to address this. s6/dumb-init etc are all against the core fundamentals of docker as docker and create another layer of abstraction. I will look into the SIGTERM issue

**Comment by ginkel** [comment]
That's also fine for me. dumb-init is a kind-of brute-force approach to work around the issue. Implementing a SIGTERM handler in Python that terminates the process on SIGTERM will also do the trick.

**Comment by nodekra** [comment]
> I am not sure that this is the correct way to address this. s6/dumb-init etc are all against the core fundamentals of docker as docker and create another layer of abstraction. I will look into the SIGTERM issue

I'ts not about layers or against docker, it's just "SIG proxy" to child process.
Take a look into docker daemon options:
```
"init": false,
"init-path": "/usr/libexec/docker-init",
```

**Comment by DirtyCajunRice** [comment]
For later consumption: https://docs.docker.com/engine/reference/run/#specify-an-init-process

After reading the above, would you agree that adding an `--init` example to documentation would be better suited/ satisfy your needs @ginkel ?

**Comment by ginkel** [comment]
@DirtyCajunRice I have to admit that I haven't used `-init` so far, the reason being that most Docker containers are "well-behaved" in this regard. Anyway, I'd expect the Docker image to be self-contained, i.e., I don't have to supply extra flags to have it play nicely.

**Comment by DirtyCajunRice** [comment]
Closing out all these old PRs. Feel Free to re-open if still valid.

**Pull request closed without merging**
