### PR TITLE
Added Pushover & HealthChecks notification

### PR DESCRIPTION
**Pull request by UniverseXXX**
Added Pushover & HealthChecks.
Readme.md updated.

### CODE REVIEW

**Comment by circa10a** [comment]
@UniverseXXX Thanks for the contribution!

It can't be merged in at this time sine ouroboros is undergoing a rewrite and is moving to an org. Once the rewrite is implemented(very soon). Changes will need to be made to the PR to make it compatible, but shouldn't be much work. Stay tuned!

**Comment by UniverseXXX** [comment]
> @UniverseXXX Thanks for the contribution!
> 
> It can't be merged in at this time sine ouroboros is undergoing a rewrite and is moving to an org. Once the rewrite is implemented(very soon). Changes will need to be made to the PR to make it compatible, but shouldn't be much work. Stay tuned!

thanks @circa10a Looking forward

**Comment by DirtyCajunRice** [comment]
To clarify, would you personally like to do the rewrite of your pull request or would you like us to implement it? I am totally fine with it either way, and i know some people want to get their feet wet!

**Comment by UniverseXXX** [comment]
> To clarify, would you personally like to do the rewrite of your pull request or would you like us to implement it? I am totally fine with it either way, and i know some people want to get their feet wet!

Feel free to use/modify the code I've added, if you'll need some extra testing let me know. Thanks.

**Comment by DirtyCajunRice** [comment]
hey man, finished up your request in the 2 prior linked pull request. looks like this: https://imgur.com/a/4R7QuRy
gonna close this out

**Comment by UniverseXXX** [comment]
> hey man, finished up your request in the 2 prior linked pull request. looks like this: https://imgur.com/a/4R7QuRy
> gonna close this out

Looks great. Many thanks for this.

**Pull request closed without merging**
