### PR TITLE
Catch self update apierror

### PR DESCRIPTION
**Pull request by circa10a**
address #230

### CODE REVIEW

**Comment by circa10a** [comment]
fixing lint now
just catching

```python
  me_created = self.client.api.create_container(**new_config)
  new_me = self.client.containers.get(me_created.get("Id"))
  new_me.start()
```

**Comment by DirtyCajunRice** [comment]
looks like you need to fix the lint errors. Also do you want to catch the whole thing or just the create?

**Comment by DirtyCajunRice** [comment]
you have to catch the create not the start. it cant create a container with a name that exists

**Comment by circa10a** [comment]
```python
try:
                me_created = self.client.api.create_container(**new_config)  <== catching create?
                new_me = self.client.containers.get(me_created.get("Id"))
                new_me.start()
                self.logger.debug('If you strike me down, I shall become \
                                   more powerful than you could possibly imagine.')
                self.logger.debug('https://bit.ly/2VVY7GH')
                sleep(30)
            except APIError as e:
                self.logger.error("Self update failed.")
                self.logger.error(e)
```

**Pull request merged**
