### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by nemchik**
Upgrade to https://github.com/caronc/apprise/releases/tag/v0.8.2 to fix https://github.com/caronc/apprise/pull/180

### CODE REVIEW

**Comment by viveksupe** [comment]
Facing the same issue. +1 on the changes.

**Comment by viveksupe** [comment]
@DirtyCajunRice @circa10a Thoughts?

**Comment by datablitz7** [comment]
This should fix broken discord notifications

**Comment by circa10a** [comment]
I'm good with it.
@DirtyCajunRice you want this to go to `develop`?

**Comment by DirtyCajunRice** [comment]
yes develop

**Comment by viveksupe** [comment]
Created develop Pull Request: https://github.com/pyouroboros/ouroboros/pull/352

**Comment by nemchik** [comment]
@DirtyCajunRice I've changed the target branch. Can this merge?

**Pull request merged**
