### PR TITLE
Add useful informations in notification title

### PR DESCRIPTION
**Pull request by nicoulaj**
In some contexts you only see the notification title, so it would be nice if it contained the most useful information. Here is a proposed change.

### CODE REVIEW

**Comment by DirtyCajunRice** [comment]
What are those aforementioned contexts?

**Comment by nicoulaj** [comment]
Notifications on smartphone, I use Gotify, on Android depending how you setup notifications you only see the title or an excerpt of the body.

**Comment by DirtyCajunRice** [comment]
So as notifications are designed to be. A notification title is just that. A title. Not data. The purpose of not showing relevant information in the title is exactly so that people can hide the information they dont want seen. I personally think this goes against that mentality, but ill leave it up to see if the consensus wants it!

**Comment by andrewjmetzger** [comment]
Chiming in here against this PR, at least in its current state.

@nicoulaj This might be useful in a limited scope, but I get the sense that it would not be desirable to the wider user base. I would support this if it were a *configurable* option, but not the *only* one.

Users should, ideally, be able to choose whether such content --which is usually present in the notification body -- should be displayed in the title as well.

**Comment by DirtyCajunRice** [comment]
I like the thought of flagging the "verbosity" of the title in the way @andrewjmetzger explained it. Would you like to take a stab at it @nicoulaj ?

**Comment by nicoulaj** [comment]
No

**Pull request closed without merging**
