### PR TITLE
Notification update

### PR DESCRIPTION
**Pull request by mathcantin**
Hi,
Here a big change on notifications but there are no breaking changes. There are two goals:

### Add possibility to edit the notification message
Apprise is good to customize the notification service to use, but we need a way to customize the message. To do that I add templating message with jinja2 and an option template_file.

By default, if you don't specify template_file option, we use a default template depending if your running in container or swarm mode. If you add template_file option (don't forget to mount the file or the config in ouroboros container) that template is use. Available tokens for template are : hostname, socket, total_monitored, total_updated, updated_tuples, updated_tuples.

### Override notifiers for a container or service
You can use the label `com.ouroboros.notifiers` to override default notifiers only for this container/service.

Use case:
I use slack notification. I want all notification come to #devops channel, but for stack B I want to notify team B and for stack C I want to turn off notification.

To try I use this stack:
```
version: "3.6"

configs:
  ouroboros-template:
    file: template.j2

services:
  ouroboros:
    image: pyouroboros/ouroboros
    environment: 
      NOTIFIERS: "slack://${SLACK_TOKEN}/#devops-monitoring"
      TZ: "America/Montreal"
      TEMPLATE_FILE: "/template.j2"
      SWARM: "true"
    configs:
      - source: ouroboros-template
        target: /template.j2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

With this template file:
```

{% for service, old_image, new_image in updated_tuples %}
    {{ service.name }} updated from {{ old_image }} to {{ new_image }}
{% endfor %}
```

And I use this stack to try it:
```
version: "3.6"

services:
  testA:
    image: myorg/testimage

  testB:
    image: myorg/testimage
    deploy:
      labels:
        com.ouroboros.notifiers: "slack://${SLACK_TOKEN}/#devops-monitoring slack://${SLACK_TOKEN}/#teamB"

  testC:
    image: myorg/testimage
    deploy:
      labels:
        com.ouroboros.notifiers: ""
```

On update testA will send notification to channel devops-monitoring , testB on channel devops-monitoring  and teamB, and testC will not send notification.

Of course that work also with container without swarm mode:
```
docker run -d -it --label com.ouroboros.notifiers="" myorg/testimage
```

I'm open for any comment and review.

### CODE REVIEW

**Comment by DirtyCajunRice** [comment]
i understand you have put a lot of changes into this and i appreciate your enthusiasm, but i dont believe that notification templating is really a big deal nor something anyone has asked for. Notifications are only here to give a simplistic alert of a change, not address a compny-wide email

**Comment by flopon** [comment]
In fact, it's something that I planned to watch as well !

I also wonder about the possibility of customizing / removing the launch message: I am currently testing ouroboros to update an IoT fleet, and because of the lack of flag --device in swarm mode, I use ouroboros in global swarm mode (so one ouroboros container per device) for update non-swarm containers -> this is a LOT of launch message during my tests!

**Comment by mathcantin** [comment]
@flopon I add an option for you in that pull request. --skip-start-notif

**Comment by flopon** [comment]
Thx @mathcantin !

**Comment by mathcantin** [comment]
I close this pull request. I think this project does not want this type of update. I prefer to launch a folk https://github.com/docupdater/docupdater

**Pull request closed without merging**
