### PR TITLE
Add Warning for label_enable not set while using labels_only

### PR DESCRIPTION
**Pull request by larsderidder**
I spend a few minutes confused because I set labels_only to true, expecting labels to work. However, it required labels_enable to be set to true as well.

I don't see a scenario where setting labels_only but not enabling labels makes sense, so the update simply sets labels_enable to true if labels_only is true.

### CODE REVIEW

**Comment by DirtyCajunRice** [comment]
This was intentionally left as it was to allow "turning off" label_enable temporarily. I feel as though this is better suited in the wiki under the labels_only section. If you would like to add a `logger.warning('labels_only enabled but not in use without label_enable')` I see no issue with that. Thoughts?

**Comment by larsderidder** [comment]
I see, that makes sense. What about setting label_enable to true only if it's omitted and labels_only is true? Setting it to false explicitly could still work, and we could then show the warning.

**Comment by DirtyCajunRice** [comment]
false/commented out is personal preference. its much easier (read lazier) to just comment out the env line in compose than to type false. so i see that backfiring ya know?

**Comment by DirtyCajunRice** [comment]
How we doing on this one

**Comment by larsderidder** [comment]
Updated.

**Pull request merged**
